# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
before_script:
- docker info
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
build:
  tags:
  - shell
  stage: build
  script:
  - docker build -t $CI_REGISTRY/docker/nginx-php-1crm:latest .
  - docker push $CI_REGISTRY/docker/nginx-php-1crm:latest
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
