stages:
  - build
  - test
include:
  - template: Security/SAST.gitlab-ci.yml
variables:
  # Version aktualisieren bei Änderung der Download-URL
  VERSION: "8.7.4"


before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  tags:
    - shell
  stage: build
  script:
    - "branch=$VERSION && [[ $CI_COMMIT_REF_NAME != 'master' ]] && branch=$VERSION-$CI_COMMIT_REF_NAME"
    - docker pull webdevops/php-nginx:8.1
    - docker build -t $CI_REGISTRY/docker/nginx-php-1crm:$branch .
    - docker push $CI_REGISTRY/docker/nginx-php-1crm:$branch
    - echo "Pushed Image Tag $branch"
    
build_latest:
  tags: 
    - shell
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME == "main"
  script:
    - docker build -t $CI_REGISTRY/docker/nginx-php-1crm:latest .
    - docker push $CI_REGISTRY/docker/nginx-php-1crm:latest
    - echo "Pushed Image Tag $branch"


sast:
  stage: test
  tags:
    - docker
