stages:
  - build
  - test
include:
  - template: Security/SAST.gitlab-ci.yml

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  tags:
    - shell
  stage: build
  script:
    - docker build -t $CI_REGISTRY/docker/nginx-php-1crm:latest .
    - docker push $CI_REGISTRY/docker/nginx-php-1crm:latest

sast:
  stage: test
  tags:
    - docker
