stages:
  - build
  - test
include:
  - template: Security/SAST.gitlab-ci.yml

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  tags:
    - shell
  stage: build
  script:
    - "branch='latest' && [[ $CI_COMMIT_BRANCH != 'master' ]] && branch=$CI_COMMIT_BRANCH"
    - docker build -t $CI_REGISTRY/docker/nginx-php-1crm:$branch .
    - docker push $CI_REGISTRY/docker/nginx-php-1crm:$branch
    - echo "Pushed Image Tag $branch"
    


sast:
  stage: test
  tags:
    - docker
