stages:
  - build
  - test
include:
  - template: Security/SAST.gitlab-ci.yml
variables:
  # Version aktualisieren bei Änderung der Download-URL
  VERSION: "8.7"


before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  tags:
    - shell
  stage: build
  script:
    - "branch=$VERSION && [[ $CI_COMMIT_REF_NAME != 'master' ]] && branch=$VERSION-$CI_COMMIT_REF_NAME"
    - docker pull webdevops/php-nginx:8.1
    - docker build -t $CI_REGISTRY/docker/nginx-php-1crm:$branch .
    - docker push $CI_REGISTRY/docker/nginx-php-1crm:$branch
    - echo "Pushed Image Tag $branch"
    
build_latest:
  tags: 
    - shell
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME == "main"
  script:
    # 8.7.4 am 14.03.2023 durch 8.7 ersetzt, um Minor-Versionen im selben Tag aktualisiert zu bekommen
    - docker build -t $CI_REGISTRY/docker/nginx-php-1crm:8.7.4 .
    - docker push $CI_REGISTRY/docker/nginx-php-1crm:8.7.4
    # latest eigentlich nicht verwenden! Da bei einem Major-Update PHP inkompatibilitäten auftreten können
    - docker build -t $CI_REGISTRY/docker/nginx-php-1crm:latest .
    - docker push $CI_REGISTRY/docker/nginx-php-1crm:latest
   


sast:
  stage: test
  tags:
    - docker
